messages:
  # /bruh command
  prefix: '&b&lBruhCMD &8&l>>'
  bruh-message: '&cB&er&au&9h'
  reload-message: '&9BruhCMD successfully reloaded.'
  # General invalid messages
  no-permission-message: '&cNo permission, contact an administrator if you think this is an error.'
  console-cannot-use: '&c&lHey! &8You are not allowed to use this command in console.'
  not-enabled: '&cThis command is disabled by server administrators.'
  player-not-found: '&cNo online players were found with that name. Did you spell it right?'
  # Other Commands
  sus-subtitle: 'Sabotage, eliminate, and betray the other crewmates.'
  sus-player-message: 'no'
enabled-commands:
  cutg: false
  sus: false
  pop: true
  yeet: false
  yeet-others: false
  joe: false
  cyberpunk: false
  creeper: false
  bomb: false
  dragon: false
commands:
  #note, you might wanna research the Spigot material names to change the reward item
  reward-item: DIAMOND
  reward-amount: 20
  #NOTE: Powers over 20 can and probably will crash servers, would not recommend it
  bomb-power: 10
  fire: true