name: BruhCMD
version: 1.2.5
author: Icynnac
main: me.Icynnac.bruhcmd.Main
description: idk

commands:
  bruh:
    description: The command that allows you to see bruh.
  bruh about:
    description: The general info for BruhCMD.
    permission: bruhcmd.about
  bruh reload:
    description: Reloads the plugin.
    permission: bruhcmd.reload
