name: BruhCMD
version: 1.4
author: Icynnac
main: me.Icynnac.bruhcmd.Main
description: idk

commands:
  bruh:
    description: The command that allows you to see bruh.
  bruh about:
    description: The general info for BruhCMD.
    permission: bruhcmd.about
  bruh reload:
    description: Reloads the plugin.
    permission: bruhcmd.reload
  cutg:
    description: Someone likes ya cut G
    permission: bruhcmd.cutg
  pop:
    description: pop cat + pop command
  yeet:
    description: yeet
    permission: bruhcmd.yeet
