name: BruhCMD
version: 1.6
author: Icynnac
main: me.icynnac.bruhcmd.Main
description: idk
commands:
  bruh:
    description: The command I thought of on that November 15th, 2020.
  bruh reload:
    description: Reloads the config.yml
    permission: bruhcmd.reload
  sus:
    description: you are sus.
    permission: bruhcmd.sus
  cutg:
    description: someone likes ya cut g
    permission: bruhcmd.cutg
  yeet:
    description: yeet yourself into the stratosphere.
    permission: bruhcmd.yeet
  pop:
    description: pop cat
  bruhcmd:
    description: a ui for basic stuff in bruhcmd
    permission: bruhcmd.about
  joe:
    description: joe mama joke kicks people from server
  cyberpunk:
    description: aka hack fortnite and die for it
  bomb:
    description: boom.
  creeper:
    description: awww man
